---
abstract: 'Content Addressabe Storage API, and implementations'
author:
  - 'Michael Conrad <mconrad@intellitree.com>'
build_requires:
  Data::Dumper: 0
  File::stat: 0
  Path::Class: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DataStore-CAS
requires:
  Carp: 0
  Digest: 1.16
  File::Spec: 3.33
  File::Spec::Functions: 0
  File::Temp: 0.22
  Moo: 1.000007
  Moo::Role: 0
  Scalar::Util: 0
  Symbol: 0
  Try::Tiny: 0
  parent: 0
  perl: 5.008
  strict: 0
  warnings: 0
version: 0.0200
